// ------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 CSV 툴에 의해 자동 생성되었습니다. 절대 수동으로 수정하지 마세요.
//     원본 파일: TestTable.csv
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CoreEngine.GameData.Test
{
    public static class TestRecordKeys
    {
        /// <summary> 엑셀 행: 2 | 원본 PK: 1 </summary>
        public const ulong _1
            = 1ul;

        /// <summary> 엑셀 행: 3 | 원본 PK: 2 </summary>
        public const ulong _2
            = 2ul;

        /// <summary> 엑셀 행: 4 | 원본 PK: 3 </summary>
        public const ulong _3
            = 3ul;

        /// <summary> 엑셀 행: 5 | 원본 PK: 4 </summary>
        public const ulong _4
            = 4ul;

        /// <summary> 엑셀 행: 6 | 원본 PK: 5 </summary>
        public const ulong _5
            = 5ul;

        /// <summary> 엑셀 행: 7 | 원본 PK: 6 </summary>
        public const ulong _6
            = 6ul;

        /// <summary> 엑셀 행: 8 | 원본 PK: 7 </summary>
        public const ulong _7
            = 7ul;

        /// <summary> 엑셀 행: 9 | 원본 PK: 8 </summary>
        public const ulong _8
            = 8ul;

        /// <summary> 엑셀 행: 10 | 원본 PK: 9 </summary>
        public const ulong _9
            = 9ul;

        /// <summary> 엑셀 행: 11 | 원본 PK: 10 </summary>
        public const ulong _10
            = 10ul;

        /// <summary> 엑셀 행: 12 | 원본 PK: 11 </summary>
        public const ulong _11
            = 11ul;

        /// <summary> 엑셀 행: 13 | 원본 PK: 12 </summary>
        public const ulong _12
            = 12ul;

        /// <summary> 엑셀 행: 14 | 원본 PK: 13 </summary>
        public const ulong _13
            = 13ul;

        /// <summary> 엑셀 행: 15 | 원본 PK: 14 </summary>
        public const ulong _14
            = 14ul;

        /// <summary> 엑셀 행: 16 | 원본 PK: 15 </summary>
        public const ulong _15
            = 15ul;

        /// <summary> 엑셀 행: 17 | 원본 PK: 16 </summary>
        public const ulong _16
            = 16ul;

        /// <summary> 엑셀 행: 18 | 원본 PK: 17 </summary>
        public const ulong _17
            = 17ul;

        /// <summary> 엑셀 행: 19 | 원본 PK: 18 </summary>
        public const ulong _18
            = 18ul;

        /// <summary> 엑셀 행: 20 | 원본 PK: 19 </summary>
        public const ulong _19
            = 19ul;

        /// <summary> 엑셀 행: 21 | 원본 PK: 20 </summary>
        public const ulong _20
            = 20ul;

    }
}
