// ------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 CSV 툴에 의해 자동 생성되었습니다. 절대 수동으로 수정하지 마세요.
//     원본 파일: TestRefereceTable.csv
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CoreEngine.GameData.Test
{
    public static class TestReferenceRecordKeys
    {
        /// <summary> 엑셀 행: 2 | 원본 PK: Ref_01 </summary>
        public const ulong Ref_01
            = 4604167603703894700ul;

        /// <summary> 엑셀 행: 3 | 원본 PK: Ref_02 </summary>
        public const ulong Ref_02
            = 11593950751718983560ul;

        /// <summary> 엑셀 행: 4 | 원본 PK: Ref_03 </summary>
        public const ulong Ref_03
            = 13161340787375162469ul;

        /// <summary> 엑셀 행: 5 | 원본 PK: Ref_04 </summary>
        public const ulong Ref_04
            = 16260360966871528159ul;

        /// <summary> 엑셀 행: 6 | 원본 PK: Ref_05 </summary>
        public const ulong Ref_05
            = 13172524941829206638ul;

    }
}
