using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using CoreEngine.Helpers;

namespace CoreEditor.GameData
{
    public static class KeyClassGenerator
    {
        public static void Generate(TextAsset csvAsset, Type recordType, List<string> rawKeys)
        {
            string csvPath = AssetDatabase.GetAssetPath(csvAsset);
            string dir = Path.GetDirectoryName(csvPath);
            string className = recordType.Name + "Keys";
            string scriptPath = Path.Combine(dir, className + ".cs");

            string nameSpace = recordType.Namespace ?? "CoreEngine.GameData";

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     이 코드는 CSV 툴에 의해 자동 생성되었습니다. 절대 수동으로 수정하지 마세요.");
            sb.AppendLine($"//     원본 파일: {csvAsset.name}.csv");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine($"namespace {nameSpace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            HashSet<string> usedVarNames = new HashSet<string>();

            for (int i = 0; i < rawKeys.Count; i++)
            {
                string rawKey = rawKeys[i];
                string varName = SanitizeToVariableName(rawKey);
                ulong hashValue = HashHelper.StringToId(rawKey);

                if (usedVarNames.Contains(varName))
                {
                    varName = $"{varName}_{i + 2}";
                }
                usedVarNames.Add(varName);

                sb.AppendLine($"        /// <summary> 엑셀 행: {i + 2} | 원본 PK: {rawKey} </summary>");
                sb.AppendLine($"        public const ulong {varName}");
                sb.AppendLine($"            = {hashValue}ul;");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(scriptPath, sb.ToString(), System.Text.Encoding.UTF8);
            AssetDatabase.ImportAsset(scriptPath, ImportAssetOptions.ForceUpdate);
        }

        private static string SanitizeToVariableName(string rawKey)
        {
            if (string.IsNullOrWhiteSpace(rawKey)) return "_EmptyKey";

            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            if (char.IsDigit(rawKey[0]))
            {
                sb.Append('_');
            }

            foreach (char c in rawKey)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }
            return sb.ToString();
        }
    }
}